[package]
name = "rdfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
schemafy = "0.6.0"
serde_variant = "0.1.1"

[build-dependencies]
reqwest = { version = "0.11.8", features = ["blocking"] }
