[package]
name = "rdfmt"
version = "0.1.0"
edition = "2021"

repository = "https://github.com/sksat/rdfmt-rs"
authors = ["sksat <sksat@sksat.net>"]
readme = "README.md"
description = "Reviewdog Diagnostic Format Rust Library"
license = "MIT"

[dependencies]
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.74"
schemafy = "0.6.0"
serde_variant = "0.1.1"

[build-dependencies]
reqwest = { version = "0.11.8", features = ["blocking"] }

[dev-dependencies]
prettydiff = "0.5.1"
