name: Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    paths:
      - '.github/workflows/release.yml'

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Rust toolchain
        id: toolchain
        run: |
          echo -n "::set-output name=toolchain::"
          awk -F'[ ="]+' '$1 == "channel" { print $2 }' rust-toolchain
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}

      - name: package
        run: |
          cargo clean
          cargo package --features build-with-local-schema

      - name: publish
        run: |
          cargo publish --dry-run --features default,build-with-local-schema --allow-dirty --no-verify
