name: Rust

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths:
      - 'src/**'
      - 'build.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain'
      - '.github/workflows/rust.yml'

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.7.3

      - name: reviewdog / clippy
        uses: sksat/action-clippy@v1.0.0
        with:
          reporter: github-pr-review
          clippy_flags: --all-features

      - name: unit test
        run: cargo test

      - name: generate document
        run: cargo doc
